### ISSUE TITLE
How to install in Doom-Emacs

### ISSUE THREAD

**Issue by OrionRandD** [isamert/empv.el#1]
How do I install this package in Doom-Emacs.
I think that quelpa will mess up my config.el
and I do not want to install it by using the load-path.
Since I want to get new updates...

**Comment by isamert** [comment]
I will publish this package on MELPA soon (hopefully), then you can use that. But for now, a quick search gave me this:

```
(package! empv :recipe (:fetcher github :repo "isamert/empv.el"))
```

This also uses quelpa but I guess it's included in Doom already. I might be mistaken. Can you try and report if it works or not? If you don't want this method (because of not getting the updates) you might want to wait a bit until I figure how to publish this package on MELPA.

**Comment by OrionRandD** [comment]
I've managed to install it in doom. Everything seemed to be ok. If I search
for, say, Emacs, I can get lots of video streams to play in the minibuffer.
Then I choose one of them, but MPV does not show up. There is no error
messages in the Messages buffer.
Then I had to comment my configuration.
Anyway, I'm using "ytel" package - it is very similar to "empv". It uses
invidious instances as well with the add that it shows a list of instances
to be chosen in case one instance fail. Have a look at "ytel" as well.
Perhaps you can get some ideas from that...
Thx :)


Em ter, 11 de mai de 2021 15:03, İsa Mert Gürbüz ***@***.***>
escreveu:

**Comment by isamert** [comment]
I should probably make this more visible, but essentially `empv` is focused more on audio so the Youtube functionality will only play the sound by default. If you want to watch the video, you should call `empv-toggle-video` afterwards (and then re-call it to hide it again). In addition to that, you need to add the following to your configuration before using empv:

```
(add-to-list empv-mpv-args "--ytdl-format=best")
```

Here is the [relevant part](https://github.com/isamert/empv.el#a-note-about-empv-toggle-video) of the README.

Feel free to open a new issue if you decide to gave it another shot and if it's still not working for you. Thanks!
