### ISSUE TITLE
consult-empv-youtube brings the following error/warning

### ISSUE THREAD

**Issue by poulpoulsen** [isamert/empv.el#12]
hello,
first thank you to fix the previous error i reported.
its fixed!
but after select something, the following occurs.
it seems, that something goes wrong.

any ideas?
`
curl: (3) URL using bad/illegal format or missing URL
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
`

**Comment by isamert** [comment]
Hmm this is interesting, are you using `consult-empv-youtube-tabulated` or did you set `empv-youtube-use-tabulated-results` to a non-nil value? If so do `(setq empv-youtube-use-tabulated-results nil)` and try using `consult-empv-youtube` to check if it's working properly. `curl` is not used anywhere else, so that may be the culprit.

Otherwise, can you describe what exactly are you doing before this message pops up? Is this happening after you select a search term or is this happening after you select a video to start playing from the results? Also doing `toggle-debug-on-error` gives a stacktrace of the error (if there are any errors), can you post the stack trace?

**Comment by poulpoulsen** [comment]
hello,
the warning is gone, if i set the tabulated-results to nil.
unfortunately debug-on-error doesnt fit, because it is not an error, it is a warning.

any idea?

**Comment by isamert** [comment]
Got it, I have some ideas. I will try to pin it down and fix it within the day.

**Comment by isamert** [comment]
I (hopefully) fixed issue but I also added some useful logging in case that it's not fixed. If it is still happening, please do `empv-toggle-debug` first and then repeat the process that is causing the issue and send me the output.

**Comment by poulpoulsen** [comment]
hello,
unfortunately the error/warning exists. here is the debug output:
`
Contacting host: y.com.sb:443
(empv) Starting MPV.
(empv) >> {"command":["observe_property",-111368797060202334,"metadata"],"request_id":"-111368797060202334"}
empv :: Playing https://youtu.be/watch?v=rIzLq2q4K1w# Klaus Schulze - Shoreless Two
(empv) handle-metadata-change <> nil
(empv) >> {"command":["get_property","media-title"],"request_id":"-1757542988954687995"}
(empv) << data: ((request_id . -111368797060202334) (error . success)), request_id: -111368797060202334, has-cb?: t, remove-cb? :nil
(empv) handle-metadata-change <> nil
(empv) >> {"command":["get_property","media-title"],"request_id":"-1424983950379714892"}
(empv) << data: ((event . property-change) (id . -111368797060202334) (name . metadata)), request_id: nil, has-cb?: t, remove-cb? :nil
empv :: watch?v=rIzLq2q4K1w# Klaus Schulze - Shoreless Two
(empv) <> Removing callback.
(empv) << data: ((data . watch?v=rIzLq2q4K1w# Klaus Schulze - Shoreless Two) (request_id . -1757542988954687995) (error . success)), request_id: -1757542988954687995, has-cb?: t, remove-cb? :empv :: watch?v=rIzLq2q4K1w# Klaus Schulze - Shoreless Two
empv :: watch?v=rIzLq2q4K1w# Klaus Schulze - Shoreless Two
(empv) <> Removing callback.
(empv) << data: ((data . watch?v=rIzLq2q4K1w# Klaus Schulze - Shoreless Two) (request_id . -1424983950379714892) (error . success)), request_id: -1424983950379714892, has-cb?: t, remove-cb? :empv :: watch?v=rIzLq2q4K1w# Klaus Schulze - Shoreless Two
(empv) << data: ((event . tracks-changed)), request_id: nil, has-cb?: nil, remove-cb? :nil [2 times]
(empv) << data: ((event . metadata-update)), request_id: nil, has-cb?: nil, remove-cb? :nil
(empv) << data: ((event . audio-reconfig)), request_id: nil, has-cb?: nil, remove-cb? :nil [2 times]
(empv) << data: ((event . file-loaded)), request_id: nil, has-cb?: nil, remove-cb? :nil
(empv) handle-metadata-change <> ((major_brand . mp42) (minor_version . 0) (compatible_brands . isommp42) (creation_time . 2016-08-27T04:30:25.000000Z))
(empv) >> {"command":["get_property","media-title"],"request_id":"729635624932054451"}
(empv) << data: ((event . property-change) (id . -111368797060202334) (name . metadata) (data (major_brand . mp42) (minor_version . 0) (compatible_brands . isommp42) (creation_time . 2016-08-27T04:30:25.000000Z))), request_id: nil, has-cb?: t, remove-cb? :nil
empv :: Klaus Schulze - Shoreless Two
(empv) <> Removing callback.
(empv) << data: ((data . Klaus Schulze - Shoreless Two) (request_id . 729635624932054451) (error . success)), request_id: 729635624932054451, has-cb?: t, remove-cb? :empv :: Klaus Schulze - Shoreless Two
(empv) << data: ((event . audio-reconfig)), request_id: nil, has-cb?: nil, remove-cb? :nil
(empv) << data: ((event . video-reconfig)), request_id: nil, has-cb?: nil, remove-cb? :nil [2 times]
(empv) << data: ((event . playback-restart)), request_id: nil, has-cb?: nil, remove-cb? :nil
`

does it help?

**Comment by isamert** [comment]
Hmm, I don't see any of the new logs I've added with the latest commit, did you update the empv before collecting the logs? Because there should be at least one log starting with `Dowloading thumbnail using ...` if you call `M-x consult-empv-youtube-tabulated`.

**Comment by poulpoulsen** [comment]
hello again,
i just called the command consult-empv-youtube-tabulated after i set debug.
here is the output.
is it better?

`
empv :: Debug mode is t
Contacting host: y.com.sb:443
(empv) Starting MPV.
(empv) >> {"command":["observe_property",765215481868314892,"metadata"],"request_id":"765215481868314892"}
empv :: Playing https://youtu.be/watch?v=-ZcEY1tcHPE# Klaus Schulze - Unheilbar Deutsch
(empv) handle-metadata-change <> nil
(empv) >> {"command":["get_property","media-title"],"request_id":"1724736718162724127"}
(empv) << data: ((request_id . 765215481868314892) (error . success)), request_id: 765215481868314892, has-cb?: t, remove-cb? :nil
(empv) handle-metadata-change <> nil
(empv) >> {"command":["get_property","media-title"],"request_id":"-421030610264060351"}
(empv) << data: ((event . property-change) (id . 765215481868314892) (name . metadata)), request_id: nil, has-cb?: t, remove-cb? :nil
empv :: watch?v=-ZcEY1tcHPE# Klaus Schulze - Unheilbar Deutsch
(empv) <> Removing callback.
(empv) << data: ((data . watch?v=-ZcEY1tcHPE# Klaus Schulze - Unheilbar Deutsch) (request_id . 1724736718162724127) (error . success)), request_id: 1724736718162724127, has-cb?: t, remove-cb? :empv :: watch?v=-ZcEY1tcHPE# Klaus Schulze - Unheilbar Deutsch
empv :: watch?v=-ZcEY1tcHPE# Klaus Schulze - Unheilbar Deutsch
(empv) <> Removing callback.
(empv) << data: ((data . watch?v=-ZcEY1tcHPE# Klaus Schulze - Unheilbar Deutsch) (request_id . -421030610264060351) (error . success)), request_id: -421030610264060351, has-cb?: t, remove-cb? :empv :: watch?v=-ZcEY1tcHPE# Klaus Schulze - Unheilbar Deutsch
(empv) << data: ((event . tracks-changed)), request_id: nil, has-cb?: nil, remove-cb? :nil [2 times]
(empv) << data: ((event . metadata-update)), request_id: nil, has-cb?: nil, remove-cb? :nil
(empv) << data: ((event . audio-reconfig)), request_id: nil, has-cb?: nil, remove-cb? :nil [2 times]
(empv) << data: ((event . file-loaded)), request_id: nil, has-cb?: nil, remove-cb? :nil
(empv) handle-metadata-change <> ((major_brand . mp42) (minor_version . 0) (compatible_brands . isommp42) (creation_time . 2022-05-12T21:58:26.000000Z))
(empv) >> {"command":["get_property","media-title"],"request_id":"-963695655773388559"}
(empv) << data: ((event . property-change) (id . 765215481868314892) (name . metadata) (data (major_brand . mp42) (minor_version . 0) (compatible_brands . isommp42) (creation_time . 2022-05-12T21:58:26.000000Z))), request_id: nil, has-cb?: t, remove-cb? :nil
empv :: Klaus Schulze - Unheilbar Deutsch
(empv) <> Removing callback.
(empv) << data: ((data . Klaus Schulze - Unheilbar Deutsch) (request_id . -963695655773388559) (error . success)), request_id: -963695655773388559, has-cb?: t, remove-cb? :empv :: Klaus Schulze - Unheilbar Deutsch
(empv) << data: ((event . audio-reconfig)), request_id: nil, has-cb?: nil, remove-cb? :nil
(empv) << data: ((event . video-reconfig)), request_id: nil, has-cb?: nil, remove-cb? :nil [2 times]
(empv) << data: ((event . playback-restart)), request_id: nil, has-cb?: nil, remove-cb? :nil
`

**Comment by isamert** [comment]
Sorry for not replying your last comment, completely missed it in the notifications :/ Feel free to reopen the issue if you are still having this issue on the latest main branch. Closing it for now.
