### ISSUE TITLE
Request: Add a function for the --start= flag in mpv

### ISSUE THREAD

**Issue by Kenneth-Mata** [isamert/empv.el#13]

**Comment by isamert** [comment]
What should be the interface for this? A function like `(empv-play-starting-at <path> <mm:ss>)`?

**Comment by isamert** [comment]
I added two functions:

- `empv-seek` -> This let's you jump wherever you want on the file. (It can be absolute or relative etc.)
- `empv-save-and-exit` -> This will make empv remember the last position of current file. Playing that file later will seek to the previous position on start. This might be also useful for your use case. Also take a look at this functions documentation on README to make this the default behavior for every file.

I hope there functions covers your use case, let me know if not.

**Comment by Kenneth-Mata** [comment]
Hi, was this function changed recently in some way? i'm trying to use it interactively and get multiple errors depending on the type of empv-seek i'm trying to use

`How?  (relative, absolute, relative-percent, absolute-percent, keyframes, exact, ?): 
funcall-interactively: Wrong type argument: sequencep, 114
How?  (relative, absolute, relative-percent, absolute-percent, keyframes, exact, ?): 
funcall-interactively: Wrong type argument: sequencep, 97
How?  (relative, absolute, relative-percent, absolute-percent, keyframes, exact, ?): 
funcall-interactively: Wrong type argument: sequencep, 114
How?  (relative, absolute, relative-percent, absolute-percent, keyframes, exact, ?): 
funcall-interactively: Wrong type argument: sequencep, 97
How?  (relative, absolute, relative-percent, absolute-percent, keyframes, exact, ?): 
funcall-interactively: Wrong type argument: sequencep, 107
How?  (relative, absolute, relative-percent, absolute-percent, keyframes, exact, ?): 
funcall-interactively: Wrong type argument: sequencep, 101` 
(when using each of the options in order)
this is the input in found when i look at the Messages buffer, i have tried using numbers and strings, however the functions work as usual when used through an evaluated sexp

**Comment by isamert** [comment]
Hi @Kenneth-Mata 

Only the interactive usage is changed, it was using `completing-read` before to let you select a type (relative, absolute etc.) but now it uses `read-multiple-choice`. I started keeping a CHANGELOG file, you can also take a look at that.

How are you calling the function exactly? `M-x empv-seek` or `(funcall-interactively ...)`? If it's the latter, you don't need to use `funcall-interactively`, you can simply do `(empv-seek "33:27" '("absolute"))` or `(empv-seek "40" '("relative"))` etc.

**Comment by Kenneth-Mata** [comment]
i have a keybinding for empv-seek which prompts this
![2022-09-20_22-13](https://user-images.githubusercontent.com/92641443/191392275-dffb89ed-a10b-4106-9d29-518e73c9289e.png)
here i'm targeting *exact* 
![2022-09-20_22-14](https://user-images.githubusercontent.com/92641443/191392391-9d9c3582-c0bb-4a4a-81a7-82936fe153b6.png)
and get 
![2022-09-20_22-15](https://user-images.githubusercontent.com/92641443/191392421-14291f94-5516-4181-a581-d988815e676a.png)
![2022-09-20_22-15_1](https://user-images.githubusercontent.com/92641443/191392499-ff2255b5-9bdd-44b3-b391-e95610be837c.png)
same if i try passing it as a string

**Comment by isamert** [comment]
Oh got it, thanks for the screenshots! Seems like I introduced a bug while reworking the action selection mechanism, should be fixed now. Can you upgrade and check it now?
