### ISSUE TITLE
Is there any way to save a playlist to a file?

### ISSUE THREAD

**Issue by abougouffa** [isamert/empv.el#14]
First, thank you for this awesome package.

I would like to know if there is a way to save a playlist to a file, and load it later?

For example, usually, I enqueue some songs from YouTube (using `consult-empv-youtube`), this works perfectly, however, there is no clear way how to save these links to a playlist so the next time I don't need to search for them again.

Note: Even when calling `empv-save-and-exit`, then exit and reopen Emacs, there is no way to reload the previous playlist!

**Comment by abougouffa** [comment]
For people facing the same issue, I've implemented this feature in hackish way, it doesn't seem to be the best way to do it, but it works until the feature gets implemented in `empv.el`.

You can add this snippet to your Emacs config, and call `M-x +empv-save-playtlist-to-file` whenever you want to save the current playlist. The playlist can be loaded then by calling `M-x empv-play-file`.

```elisp
(defvar +empv-playlist-dir empv-audio-dir)

;; Only for internal usage with `empv--cmd' callbacks
(defvar empv---pl-cb)
(defvar empv---pl-curr)
(defvar empv---pl-count)
(defvar empv---pl-playlist)

(defun +empv-get-current-playlist (&optional cb &rest args)
  (when (empv--running?)
    (setq empv---pl-cb (cons cb args))
    (setq empv---pl-playlist nil)
    (empv--cmd
     'get_property 'playlist/count
     (setq empv---pl-count it)
     (setq empv---pl-curr 0)
     (dotimes (i it)
       (empv--cmd
        'get_property (intern (format "playlist/%d/filename" i))
        (add-to-list 'empv---pl-playlist it)
        (setq empv---pl-curr (1+ empv---pl-curr))
        (when (and (eq empv---pl-count empv---pl-curr)
                   (fboundp (car empv---pl-cb)))
          ;; Call on the last element
          (apply (car empv---pl-cb) empv---pl-playlist (cdr empv---pl-cb))))))))

(defun +empv-save-playtlist-to-file (path)
  (interactive "FSave playlist to: ")
  (+empv-get-current-playlist #'+empv--save-playlist-to-file path))

(defun +empv--save-playlist-to-file (playlist &optional filename)
  (with-temp-buffer
    (insert (+str-join "\n" playlist))
    (let* ((last-pl (file-name-sans-extension (car (last (directory-files +empv-playlist-dir nil "empv-playlist-\\([[:digit:]]+\\)\\.m3u")))))
           (num (if (null last-pl) 0 (1+ (string-to-number (car (last (+str-split last-pl "-"))))))))
      (write-file (or filename (expand-file-name (format "empv-playlist-%d.m3u" num) +empv-playlist-dir))))))
```

**Comment by isamert** [comment]
Thanks for your kind words!

Just to simplify things a bit, you can use the following snippet to get all paths from the playlist:

```elisp
(empv--let-properties '(playlist)
  (let ((files (mapcar (lambda (it) (alist-get 'filename it)) .playlist)))
    ;; files is a list of items in the playlist, like
    ;; '("https://youtube.com/...", "/a/local/file.mp3")
    ;; now you can save them to an m3u file
    ))
```

I guess this is a common use case and I may add a function similar to the one you implemented above. Also it might be good to have an option to save the playlist on quit automatically and then pick up when you start empv. I'll work on this.

**Comment by abougouffa** [comment]
Thank you for the reply @isamert !

> ```emacs-lisp
> (empv--let-properties '(playlist)
>   (let ((files (mapcar (lambda (it) (alist-get 'filename it)) .playlist)))
>     ;; files is a list of items in the playlist, like
>     ;; '("https://youtube.com/...", "/a/local/file.mp3")
>     ;; now you can save them to an m3u file
>     ))
> ```

Wow, that is much elegant than my verbose solution!, however, when I tried it in Emacs as:

```elisp
(empv--let-properties '(playlist)
  (let ((files (mapcar (lambda (it) (alist-get 'filename it)) .playlist)))
    (message (car files))))
```

I got this error message:

```
error in process filter: Symbol’s value as variable is void: props-alist [2 times]
```

I'm not quite comfortable with macros! Maybe I missed something!

> I guess this is a common use case and I may add a function similar to the one you implemented above. Also it might be good to have an option to save the playlist on quit automatically and then pick up when you start empv. I'll work on this.

It would be nice to have it implemented!

**Comment by isamert** [comment]
> I got this error message:
> ```
> error in process filter: Symbol’s value as variable is void: props-alist [2 times]
> ```

I believe this is due to `lexical-binding` being `nil`. If you do `(setq lexical-binding t)` before evaluating the snippet, it'll work. Adding the following snippet to the file you are evaluating the snippet should also do the trick:

```
;; -*- lexical-binding: t; -*-
```

I strongly recommend adding this to your init file, lexical binding is simply better/more predictable than the default behavior. But please note that it may break some stuff if they are depending on the older behavior. This might be useful to understand the differences: https://www.gnu.org/software/emacs/manual/html_node/elisp/Lexical-Binding.html

**Comment by abougouffa** [comment]
Thank you for taking the time to answer, I really appreciate it!

In fact, I have `lexical-binding` enabled, I tested the snippet in a scratch buffer, even with this:

```elisp
(let ((lexical-binding t))
  (empv--let-properties '(playlist)
    (let ((files (mapcar (lambda (it) (alist-get 'filename it)) .playlist)))
      (message (car files)))))
```

I still get the same error message!

**Comment by isamert** [comment]
I guess using setq-local instead of setq is the proper way of enabling it. Because setq changes the default value and does not change it for the current buffer:

```
(setq-local lexical-binding t)
```

or you can even do `M-x elisp-enable-lexical-binding`, or both, to be absolutely sure that lexical binding is enabled :)

But I'm not sure why let-binding it did not work.

**Comment by abougouffa** [comment]
Thank you so much @isamert,

It was the lexical binding, when I set it with `setq-local` I didn't get the error.
