### ISSUE TITLE
Misspelling (I assume) of command

### ISSUE THREAD

**Issue by EJamesW** [isamert/empv.el#19]
Hi!
Thanks for writing this package. I'm already finding it a quicker and easier method for watching videos than via `emms`.

Anyway, just a little issue with the name of the playlist saving function: `empv-playtlist-save-to-file`.
I assume it's supposed to be `empv-playlist-save-to-file`?

**Comment by isamert** [comment]
Thanks for pointing this out, definitely a typo!

>  I'm already finding it a quicker and easier method for watching videos than via emms.

Glad to hear that!
