### ISSUE TITLE
unable to save playlist

### ISSUE THREAD

**Issue by tvraman** [isamert/empv.el#23]
Description: Unable to save playlist 
empv-playlist-save-to-file throws a "stringp nil" error even though
when stepping in the debugger, I can see that the playlist variable
that holds the extracted playlist property contains a list of urls.

**Comment by isamert** [comment]
There was an issue with filename selection, fixed it. Thanks for reporting!

**Comment by tvraman** [comment]
thanks for empv -- it's very nice (I speech-enabled it for Emacspeak )

github.com/tvraman/emacspeak

Couple more suggestions:

have empv-play-url accept url-under-point -- see emacspeak-empv-url
here:
https://github.com/tvraman/emacspeak/blob/master/lisp/emacspeak-empv.el#L96

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by isamert** [comment]
> thanks for empv -- it's very nice (I speech-enabled it for Emacspeak )

I'm glad that you liked it and thanks for the Emacspeak integration!

> have empv-play-url accept url-under-point -- see emacspeak-empv-url

This makes sense. I also use [embark](https://github.com/oantolin/embark) for things like this and empv.el has an embark integration. When you call `embark-act` on a URL `embark` will open a keymap that contains actions defined for a URL, including `empv-play`, `empv-enqueue` and `empv-enqueue-next`. But I may add the function you mentioned nevertheless, for user that does not use embark.

**Comment by tvraman** [comment]
I tried embark a few weekg ago, , but it didn't add much value in the eyes-free context.
-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by isamert** [comment]
Hi @tvraman, I added an interactive function called `empv-play-media-at-point` which you can use to play the url/file etc. at point by calling. Hopefully it should work on every context, eww/dired/org-mode etc. Just wanted to let you know, wanted to add this as an alternative to the embark workflow.

**Comment by tvraman** [comment]
nice!

Will update use and send any follow-up requests.


-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮
