### ISSUE TITLE
Optionally skip thumbnails

### ISSUE THREAD

**Issue by tvraman** [isamert/empv.el#26]
For Emacspeak users, it would be nice to be able to specify to empv that thumbnails need not be downloaded and displayed. Possible? Also, could you add a results-displayed-done hook or equivalent?

**Comment by isamert** [comment]
Good idea, I will add a configuration for this.

**Comment by isamert** [comment]
Now you can set `empv-youtube-thumbnail-quality` to `nil` and empv will not download thumbnails, although the thumbnail column is still there. I didn't bother removing it as it was a little bit more complex to do. Hope this works for you!
