### ISSUE TITLE
empv.el volume an mpv volume

### ISSUE THREAD

**Issue by tvraman** [isamert/empv.el#28]
volume from empv.el appears to not respect volume set in config/mpv/mpv.conf; eg if you set volume-max and volume in the conf file  --- say volume=200, manipulating volume later with empv-volume-up/down immediately sets volume to 100

**Comment by isamert** [comment]
Now it should respect the mpv configuration while using `empv-volume-up`.

**Comment by tvraman** [comment]
works like a charm, thanks!

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮
