### ISSUE TITLE
This extention Is Broken on Windows but kinda works.

### ISSUE THREAD

**Issue by fislysandi** [isamert/empv.el#33]
i tried to install this extension and it kinda works.

it launches the mpv process via mpv-start  but i get this after launching it

![image](https://github.com/isamert/empv.el/assets/45166203/efe627f8-fbc0-474d-bc54-db1a73a61d43)
 
 
![Taskmgr_cKWbPUk6I5](https://github.com/isamert/empv.el/assets/45166203/2345e592-566e-43e7-aac5-7e6970e80bef)

after that is unable to detect the mpv process and manipulate it

yt search works. as you detailed in your config to set the invidious instance url.
![emacs_c4XTRSrY5q](https://github.com/isamert/empv.el/assets/45166203/93a7103e-985e-4498-982f-6b31331cc472)

![emacs_CPmI0pbW6C](https://github.com/isamert/empv.el/assets/45166203/3038a675-7d50-4a63-84e2-729f850b23ba)

if i try to play it. it seems it cant find the mpv process but its already launched.

![emacs_XLzjgaHlG7](https://github.com/isamert/empv.el/assets/45166203/d233c7dd-da56-4d7c-9a2b-73f1578bd178)

you can troubleshoot it via firing up a quickemu virt machine. and using scoop package manager to install all applications quickly

**Comment by isamert** [comment]
This is probably because empv uses unix sockets to interact with mpv. I'll check if there is an easy way to make it work on Windows.

**Comment by isamert** [comment]
Unfortunately mpv does not support sockets on Windows and I don't have a Windows machine. I am going to close this issue but I am more than happy to support Windows, so PRs are welcome.
