### ISSUE TITLE
Please allow using yt-dlp in addition to or instead of youtube-dl

### ISSUE THREAD

**Issue by DidierSpaier** [isamert/empv.el#34]
Rationale:  https://github.com/yt-dlp/yt-dlp is a fork of youtube-dl with additional features and can replace it in most usages.

**Comment by isamert** [comment]
`mpv` already supports `yt-dlp`, see [this](https://github.com/mpv-player/mpv/blob/90543610c28f89d0a74c7cb5ede60f7b13ef2973/player/lua/ytdl_hook.lua#L16).

`empv.el` itself does not make any direct use of `youtube-dl` or `yt-dlp`, so if there is a problem on picking up `yt-dlp` then it should be an issue related to `mpv`.

Feel free to re-open the issue if you think there is an issue related to `empv.el`.
