### ISSUE TITLE
[FEATURE REQUEST] Allow customizing the tabulated YouTube output

### ISSUE THREAD

**Issue by LemonBreezes** [isamert/empv.el#35]
Hi. It would be great if I could format the tabulated YouTube results output. Specifically, in
![image](https://github.com/isamert/empv.el/assets/29102529/e2af0b1c-a98c-454f-8e42-ba6290ad56dc)
I would like to remove the words `views` and `mins` from the entries.

**Comment by isamert** [comment]
I created two functions, `empv--format-yt-views` and `empv--format-yt-duration` to construct these texts. You can re-define or advise them to turn them into something you want. I am aware that this may not be the best way to do this but I don't want to turn them into public customization options as I don't want to trap myself with these customization options in the future. Keeping them private yet easy to redefine seems the best option for now. 

Hope that works for you, let me know if you have a better idea.
