### ISSUE TITLE
[BUG] Running `empv-exit` renders tabulated results buffer useless

### ISSUE THREAD

**Issue by LemonBreezes** [isamert/empv.el#37]
Basically, when I have some tabulated YouTube search results and I call `empv-exit`, Iit breaks the tabulated results buffer in that I can no longer play any of the entries.

**Comment by isamert** [comment]
This should not happen, can you describe the steps to reproduce the issue? It was an issue on earlier versions tho, can you check if you are on the latest commit?

**Comment by isamert** [comment]
I am going to close this issue, feel free to reopen if you are still experiencing this issue.
