### ISSUE TITLE
Display YouTube video length in seconds for more precision in `*empv-yt-result*`

### ISSUE THREAD

**Issue by eval-exec** [isamert/empv.el#38]
I would like to propose displaying the length value in `x mins y secs` instead, to provide more precise information about the video duration. This change would enhance the user experience by allowing us to quickly determine the exact duration of each video.
![image](https://github.com/isamert/empv.el/assets/46400566/04501622-63bc-48dd-aa73-90287ebda548)

**Comment by isamert** [comment]
Hmm interesting, it should show something like `3.7 mins` instead of just showing `3. mins`. Anyway, it is still not precise enough. What about showing "3:45" instead of showing "3 mins 45 secs" to save some real estate? Would that work for you?

**Comment by eval-exec** [comment]
> Hmm interesting, it should show something like `3.7 mins` instead of just showing `3. mins`. Anyway, it is still not precise enough. What about showing "3:45" instead of showing "3 mins 45 secs" to save some real estate? Would that work for you?

`3:45` or `3.7 mins` are fine, I agree with you.
