### ISSUE TITLE
Browse Playlist: Feature Request

### ISSUE THREAD

**Issue by tvraman** [isamert/empv.el#40]
Feature Request: Playlist And Metadata

I found a set of nice m3u playlists here:
 BBC stations:  https://garfnet.org.uk/cms/2023/10/29/latest-bbc-hls-radio-streams/

 The m3u file has an #extinf: field listing the station name, and the
 station URL.

 I am able to play the m3u file and scroll linearly through stations
 in empv.

 Feature Request:

 Would it be possible for mpv to load the playlist file, and display a
 simple tabular UI and lists the stations and enables directly playing
 the desired station?

**Comment by isamert** [comment]
After loading the file using `empv-play-file`, mpv loads all the channels into your playlist. You can do `empv-playlist-select` and see all the channels there and switch to one that you want. Does this suit you or you prefer a tabular view instead of the `completing-read` based one?

**Comment by tvraman** [comment]
thanks, actually I discovered the feature you describe and was about to
close the issue this morning; yes, that select UI more than meets my
needs. And thanks again for empv!

--

**Comment by isamert** [comment]
> thanks, actually I discovered the feature you describe and was about to
> close the issue this morning; yes, that select UI more than meets my
> needs. And thanks again for empv!

Great to hear, thanks!
