### ISSUE TITLE
empv info line

### ISSUE THREAD

**Issue by tvraman** [isamert/empv.el#41]
*Feature Request: Move Title To Start Of Info Display

Hi,

With many sites now using hls to stream (stream is split into multiple
little files) the EMPV Info Display is getting long, and worse, the
Title is at the end. Could you perhaps consider moving the Title to
the start of that display? It's a simple edit of the format line, so I
thought  a patch was too heavy a hammer, and I also dont know if you
have other ideas there.

**Comment by isamert** [comment]
Visually it makes sense to have it at the end but I understand your use-case. I can convert the format into a template and you can edit the template and move it to beginning of the line (and get rid of unnecessary information if you want). Does this suit your use-case?

**Comment by tvraman** [comment]
A template would be awesome, thanks!

--
