### ISSUE TITLE
Selectively Suppressing Event Display

### ISSUE THREAD

**Issue by tvraman** [isamert/empv.el#42]
Custom option empv-display-events loses all info display

I set the above option to nil in the hope of reducing chatter when
playing HLS streams (see earlier issue).
However turning that switch off also entirely silences
empv-display-current because that command also calls
empv--display-event -- perhaps refactor so the custom option disables
automatic event display but allows explicit requests to go through?

**Comment by isamert** [comment]
This was definitely not intentional, fixed it. Thanks for reporting!
