### ISSUE TITLE
empv: ignores save-position-on-quit in conf file

### ISSUE THREAD

**Issue by tvraman** [isamert/empv.el#44]
empv: Ignores save-position-on-quit when set in .config/mpv.conf

I added save-position-on-quit  to my config/mpv.conf and verified at
the shell that it takes effect; position is saved on quit and resumes
at saved position.

With that set in the config/mpv.conf, empv appears to ignore this; do
we need to add a flag when launching mpv so those are respected? Was
surprized because setting volume in the conf file does take effect
with empv.

**Comment by isamert** [comment]
I'm not quite sure why config file is not picked up but you can do:

```
(add-to-list 'empv-mpv-args "--save-position-on-quit")
```

to get the same effect.

**Comment by tvraman** [comment]
Custom type mismatch on empv-mpv-args:


Hide empv-mpv-args: 
'("--save-position-on-quit" "--no-video" "--no-terminal" "--idle"
  "--input-ipc-server=/tmp/empv-socket")
    State : CHANGED outside Customize. (mismatch)
(:)    Args used while starting mpv. Hide
   This should contain --input-ipc-server=‘empv-socket-file’, also
   --idle is recommended for keeping your state.

--

**Comment by tvraman** [comment]
empv  appears to not pick up saved position even when you set that
option through empv-mpv-args.

**Comment by tvraman** [comment]
One more clarification after testing:

Problem in empv appears to be when saving not resuming.

Test:

1. Play a file from the shell  ie not with empv
2.Quit playing 
3. replaying that file -- either with mpv at the shell or empv resumes
   correctly.
   4. However if you quit playing from empv, the position appears to
      not get saved.

**Comment by tvraman** [comment]
let's not bother with this
