### ISSUE TITLE
Unable to Start empv radio on Windows 10 OS 

### ISSUE THREAD

**Issue by High-Flyer** [isamert/empv.el#48]
Unable to get empv-play-radio working on emacs.
Just want to achieve 2 things to through this package: 
* Able to play the radio and
* Get the current song playing inside the radio on the modeline or some buffer to take note of the song which's playing.

> Showing error on execution of command`M-x empv-play-radio` 
empv--make-network-process: Unknown address family

Next time when same command executed error is different,
>Showing error on Second Execution of command `M-x empv-play-radio`
empv--send-command: Buffer emacs-config.org has no process
 
## Troubleshooting Steps Taken so far:
* empv is installed through Melpa  Repository and using Elpaca package manager.
* * Made sure all the dependencies mentioned mentioned on Melpa are installed. (Everything was installed by ELpaca itself.)
* Tried running `empv-start` << this starts the process but sadly songs doesnt plays, leave showing them on modeline.
* Tried running `empv-play-radio` after the `empv-start` didnt start.
* Tried some other commands `empv-play` and inserted radio channel link didnt worked.

> System Details:
OS: Windows 10 (N)
Emacs installed through: Chocolatey Package Manager
emacs-version: GNU Emacs 29.1 (build 2, x86_64-w64-mingw32) of 2023-07-31
I have no idea where my cygwin folder for chocolatey or the msys2 setup file is at. 
Emacs package manager: Elpaca
```
Config.org (init file)
(use-package empv
  :config
  (setq empv-invidious-instance "vid.priv.au")
  (setq empv-radio-channels
	'(("SomaFM - Groove Salad" . "http://www.somafm.com/groovesalad.pls")
	  ("Totally 80s FM" . "https://zeno.fm/radio/totally-80s-fm/")))
	)
```

PS: I tried eradio and its working for me on windows, sharing just for the reference, going through which i found your fork of it for the modeline title, found program reuqires a dependency by you was : [SOCAT](https://linux.die.net/man/1/socat), Which I havnt found anywhere, searched through Chocolatey / Winget / Scoop My best guess is its part of Linux-utils.

I am very New to Emacs universe its possible i am doing very silly mistake and unable to find it.
Any Input, Suggestions or troubleshooting steps will be welcome.
Last Thank you very much for the Package.

Warm Regards
Seasons Greetings

**Comment by isamert** [comment]
Unfortunately this is about mpv JSON RPC not working properly on Windows properly. Hopefully I will tackle this in future but in mean time there are no workarounds.
