### ISSUE TITLE
Howto: Persist Playlists

### ISSUE THREAD

**Issue by tvraman** [isamert/empv.el#50]
Feature Request: I use empv to find talks on Youtube, then play some of them. I'd like to persist the ones I play into a playlist file m3u/pls on disk -- and give it a name, is there an easy way to do this?

**Comment by isamert** [comment]
Does `empv-playlist-save-to-file` work for you?

**Comment by tvraman** [comment]
That saves current playlist to file.

What I notice is that I do a search, find a bunch of talks I want to
listen to, but not necessarily immediately.

As an example try this search: "Turing Institute AI"

Shows up a series of talks. I'd like to create the playlist from search
results buffer and persist to a file for later listening.
--

**Comment by tvraman** [comment]
duh, this does what I want already:-) a runs the command empv-youtube-results-enqueue-current (found in
empv-youtube-results-mode-map), which is an interactive byte-compiled
