### ISSUE TITLE
howto: jump to live

### ISSUE THREAD

**Issue by tvraman** [isamert/empv.el#56]
as an example, bloomberg on YT: https://www.youtube.com/@markets is a playlist with over 800 items right now; how do I get it to play live -- other than by hitting n 800 times

**Comment by isamert** [comment]
What do you mean by _play live_ exactly? Jump to end of the playlist? I guess it automatically adds items in a way that the lastly added video of the playlist is played first. But if you still want to jump to the end of the playlist the easiest way would be opening `empv-playlist-select` and then hitting the up key one or two times to go over to the end of the playlist (At least this is what vertico does, behavior probably depends on your completing-read frontend). I may add a buffer based playlist manager in the future which might fix this in a better way but right now there is no other way around.

**Comment by tvraman** [comment]
You understand it correctly ie playlist.

The issue arose because of channels like Bloomberg  publishing playlists
that have  thousands of entries.
--
