### ISSUE TITLE
Show Published Date?

### ISSUE THREAD

**Issue by tvraman** [isamert/empv.el#61]
Feature Request: Would it be possible to show publisher date as a column in empv-youtube-tabulated

**Comment by isamert** [comment]
Now, by default it shows the published date. Also look at the newly
added variables `empv-youtube-tabulated-video-headers` and
`empv-youtube-tabulated-playlist-headers`. Now you can fully customize
all headers through this variables. I remember that we were talking
about removing thumbnail column completely, now it's possible through
this variables. Let me know if it works for you.

**Comment by tvraman** [comment]
Awesome, pulling and setting it up  now.
--
