### ISSUE TITLE
Feature Request: Fetch Next Set Of 20 Results

### ISSUE THREAD

**Issue by tvraman** [isamert/empv.el#66]
As empv gets better and better, one thing I miss is the ability to get the next set of results, especially when searching for popular topics like Machine Learning etc.

**Comment by isamert** [comment]
This is on my backlog for quite a bit of time, I'll get onto it soon hopefully.

**Comment by isamert** [comment]
I implemented such feature in branch `feature/load-more-youtube-results`. It would be great if you can test it and let me know if it works properly.

**Comment by tvraman** [comment]
doing it now, will report back  in a bit
--

**Comment by tvraman** [comment]
1. Pulled that branch, compiled and loaded.
2. Nit request: please add a Makefile so one can do a clean build; at
   present I compiled it in a running emacs which can be buggy.
3. The command name needs to be more discoverable -- and perhaps one
   should be able to invoke it by  scrolling the results buffer.
4. Sadly it threw a backtrace on me for now, see below:

   Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  (1+ nil)
  (empv--youtube-search (nth 0 empv--last-youtube-search) (nth 1 empv--last-youtube-search) (1+ (nth 2 empv--last-youtube-search)) #'(lambda (results) (let* ((c (nthcdr 2 empv--last-youtube-search))) (setcar c (1+ (nth 2 empv--last-youtube-search)))) (empv--youtube-tabulated-entries-append results (length empv--last-youtube-candidates)) (setq empv--last-youtube-candidates (append empv--last-youtube-candidates results))))
  (empv-youtube-results-load-more)
  (#f(compiled-function (function &rest arguments) "Like `funcall' but marks the call as interactive.\nI.e. arrange that within the called function `called-interactively-p' will\nreturn non-nil." #<bytecode 0x1008f5822b79>) empv-youtube-results-load-more)
  (apply #f(compiled-function (function &rest arguments) "Like `funcall' but marks the call as interactive.\nI.e. arrange that within the called function `called-interactively-p' will\nreturn non-nil." #<bytecode 0x1008f5822b79>) empv-youtube-results-load-more nil)
  (ad-Advice-funcall-interactively #f(compiled-function (function &rest arguments) "Like `funcall' but marks the call as interactive.\nI.e. arrange that within the called function `called-interactively-p' will\nreturn non-nil." #<bytecode 0x1008f5822b79>) empv-youtube-results-load-more)
  (apply ad-Advice-funcall-interactively #f(compiled-function (function &rest arguments) "Like `funcall' but marks the call as interactive.\nI.e. arrange that within the called function `called-interactively-p' will\nreturn non-nil." #<bytecode 0x1008f5822b79>) empv-youtube-results-load-more)
  (funcall-interactively empv-youtube-results-load-more)
  (#f(compiled-function (function &optional record-flag keys) "Call FUNCTION, providing args according to its interactive calling specs.\nReturn the value FUNCTION returns.\nThe function contains a specification of how to do the argument reading.\nIn the case of user-defined functions, this is specified by placing a call\nto the function `interactive' at the top level of the function body.\nSee `interactive'.\n\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, this is done only if an arg is read using the minibuffer.\n\nOptional third arg KEYS, if given, specifies the sequence of events to\nsupply, as a vector, if FUNCTION inquires which events were used to\ninvoke it (via an `interactive' spec that contains, for instance, an\n\"e\" code letter).  If KEYS is omitted or nil, the return value of\n`this-command-keys-vector' is used." #<bytecode 0x1008f5822b45>) empv-youtube-results-load-more record nil)
  (apply #f(compiled-function (function &optional record-flag keys) "Call FUNCTION, providing args according to its interactive calling specs.\nReturn the value FUNCTION returns.\nThe function contains a specification of how to do the argument reading.\nIn the case of user-defined functions, this is specified by placing a call\nto the function `interactive' at the top level of the function body.\nSee `interactive'.\n\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, this is done only if an arg is read using the minibuffer.\n\nOptional third arg KEYS, if given, specifies the sequence of events to\nsupply, as a vector, if FUNCTION inquires which events were used to\ninvoke it (via an `interactive' spec that contains, for instance, an\n\"e\" code letter).  If KEYS is omitted or nil, the return value of\n`this-command-keys-vector' is used." #<bytecode 0x1008f5822b45>) empv-youtube-results-load-more (record nil))
  ***@***.***+-record-current-command #f(compiled-function (function &optional record-flag keys) "Call FUNCTION, providing args according to its interactive calling specs.\nReturn the value FUNCTION returns.\nThe function contains a specification of how to do the argument reading.\nIn the case of user-defined functions, this is specified by placing a call\nto the function `interactive' at the top level of the function body.\nSee `interactive'.\n\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, this is done only if an arg is read using the minibuffer.\n\nOptional third arg KEYS, if given, specifies the sequence of events to\nsupply, as a vector, if FUNCTION inquires which events were used to\ninvoke it (via an `interactive' spec that contains, for instance, an\n\"e\" code letter).  If KEYS is omitted or nil, the return value of\n`this-command-keys-vector' is used." #<bytecode 0x1008f5822b45>) empv-youtube-results-load-more record nil)
  (apply ***@***.***+-record-current-command #f(compiled-function (function &optional record-flag keys) "Call FUNCTION, providing args according to its interactive calling specs.\nReturn the value FUNCTION returns.\nThe function contains a specification of how to do the argument reading.\nIn the case of user-defined functions, this is specified by placing a call\nto the function `interactive' at the top level of the function body.\nSee `interactive'.\n\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, this is done only if an arg is read using the minibuffer.\n\nOptional third arg KEYS, if given, specifies the sequence of events to\nsupply, as a vector, if FUNCTION inquires which events were used to\ninvoke it (via an `interactive' spec that contains, for instance, an\n\"e\" code letter).  If KEYS is omitted or nil, the return value of\n`this-command-keys-vector' is used." #<bytecode 0x1008f5822b45>) (empv-youtube-results-load-more record nil))
  (call-interactively empv-youtube-results-load-more record nil)
  (command-execute empv-youtube-results-load-more record)
  (execute-extended-command nil "empv-youtube-results-load-more" nil)
  (#f(compiled-function (function &rest arguments) "Like `funcall' but marks the call as interactive.\nI.e. arrange that within the called function `called-interactively-p' will\nreturn non-nil." #<bytecode 0x1008f5822b79>) execute-extended-command nil "empv-youtube-results-load-more" nil)
  (apply #f(compiled-function (function &rest arguments) "Like `funcall' but marks the call as interactive.\nI.e. arrange that within the called function `called-interactively-p' will\nreturn non-nil." #<bytecode 0x1008f5822b79>) execute-extended-command (nil "empv-youtube-results-load-more" nil))
  (ad-Advice-funcall-interactively #f(compiled-function (function &rest arguments) "Like `funcall' but marks the call as interactive.\nI.e. arrange that within the called function `called-interactively-p' will\nreturn non-nil." #<bytecode 0x1008f5822b79>) execute-extended-command nil "empv-youtube-results-load-more" nil)
  (apply ad-Advice-funcall-interactively #f(compiled-function (function &rest arguments) "Like `funcall' but marks the call as interactive.\nI.e. arrange that within the called function `called-interactively-p' will\nreturn non-nil." #<bytecode 0x1008f5822b79>) (execute-extended-command nil "empv-youtube-results-load-more" nil))
  (funcall-interactively execute-extended-command nil "empv-youtube-results-load-more" nil)
  (#f(compiled-function (function &optional record-flag keys) "Call FUNCTION, providing args according to its interactive calling specs.\nReturn the value FUNCTION returns.\nThe function contains a specification of how to do the argument reading.\nIn the case of user-defined functions, this is specified by placing a call\nto the function `interactive' at the top level of the function body.\nSee `interactive'.\n\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, this is done only if an arg is read using the minibuffer.\n\nOptional third arg KEYS, if given, specifies the sequence of events to\nsupply, as a vector, if FUNCTION inquires which events were used to\ninvoke it (via an `interactive' spec that contains, for instance, an\n\"e\" code letter).  If KEYS is omitted or nil, the return value of\n`this-command-keys-vector' is used." #<bytecode 0x1008f5822b45>) execute-extended-command nil nil)
  (apply #f(compiled-function (function &optional record-flag keys) "Call FUNCTION, providing args according to its interactive calling specs.\nReturn the value FUNCTION returns.\nThe function contains a specification of how to do the argument reading.\nIn the case of user-defined functions, this is specified by placing a call\nto the function `interactive' at the top level of the function body.\nSee `interactive'.\n\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, this is done only if an arg is read using the minibuffer.\n\nOptional third arg KEYS, if given, specifies the sequence of events to\nsupply, as a vector, if FUNCTION inquires which events were used to\ninvoke it (via an `interactive' spec that contains, for instance, an\n\"e\" code letter).  If KEYS is omitted or nil, the return value of\n`this-command-keys-vector' is used." #<bytecode 0x1008f5822b45>) execute-extended-command (nil nil))
  ***@***.***+-record-current-command #f(compiled-function (function &optional record-flag keys) "Call FUNCTION, providing args according to its interactive calling specs.\nReturn the value FUNCTION returns.\nThe function contains a specification of how to do the argument reading.\nIn the case of user-defined functions, this is specified by placing a call\nto the function `interactive' at the top level of the function body.\nSee `interactive'.\n\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, this is done only if an arg is read using the minibuffer.\n\nOptional third arg KEYS, if given, specifies the sequence of events to\nsupply, as a vector, if FUNCTION inquires which events were used to\ninvoke it (via an `interactive' spec that contains, for instance, an\n\"e\" code letter).  If KEYS is omitted or nil, the return value of\n`this-command-keys-vector' is used." #<bytecode 0x1008f5822b45>) execute-extended-command nil nil)
  (apply ***@***.***+-record-current-command #f(compiled-function (function &optional record-flag keys) "Call FUNCTION, providing args according to its interactive calling specs.\nReturn the value FUNCTION returns.\nThe function contains a specification of how to do the argument reading.\nIn the case of user-defined functions, this is specified by placing a call\nto the function `interactive' at the top level of the function body.\nSee `interactive'.\n\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, this is done only if an arg is read using the minibuffer.\n\nOptional third arg KEYS, if given, specifies the sequence of events to\nsupply, as a vector, if FUNCTION inquires which events were used to\ninvoke it (via an `interactive' spec that contains, for instance, an\n\"e\" code letter).  If KEYS is omitted or nil, the return value of\n`this-command-keys-vector' is used." #<bytecode 0x1008f5822b45>) (execute-extended-command nil nil))
  (call-interactively execute-extended-command nil nil)
  (command-execute execute-extended-command)

--

**Comment by isamert** [comment]
> Nit request: please add a Makefile so one can do a clean build; at

Noted, I need it myself too while developing.

> ... I compiled it in a running emacs which can be buggy.

Most possibly the reason.

How did you invoke the `empv-youtube-results-load-more` function? If
you jumped to last youtube search and then tried to load more, it
would fail. Can you make a new search by issuing
`empv-youtube-tabulated` and then try doing
`empv-youtube-results-load-more`? Then it should work from now on (if
you would also jump to the last )

> 3. The command name needs to be more discoverable -- and perhaps one
>    should be able to invoke it by  scrolling the results buffer.

I'm thinking of adding a `Load More` button at the end of the
buffer. Sorry I forgot to mention the command itself on my earlier
comment.

**Comment by tvraman** [comment]
byte-compile-file of course:-)

--

**Comment by tvraman** [comment]
was at the top of the buffer from memory.

Here is what I'd think of as ideal behavior:

1. You do a search, get 20 results.
2. Yu move through the list -- however you move.
3. You press C-v at any point; if the last result becomes current,
   pressing C-v again pulls more results and adds them to the end.
4. Now, C-v and M-v just move the buffer; if you hit the end, then you
   pull more.
5. Conceptually, think of it as "a roll of toilet paper" -- 
--

**Comment by isamert** [comment]
I meant if you used your last YouTube search to test this feature, it
may fail for the first time. Firstly, try to do a completely new
search by using `empv-youtube-tabulated` and then see if it can load
new results or not.

---

I can add the behavior you described in further iterations, maybe by
binding it to a defcustom. Noted it. But for now, I would like to keep
it this way.

**Comment by tvraman** [comment]
works!
