### ISSUE TITLE
hook after results are added?

### ISSUE THREAD

**Issue by tvraman** [isamert/empv.el#70]
Feature Request:  empv--youtube-tabulated-entries-append-hook

I presently have an entry on youtube search results hook to speak the
arrival of the results.

empv--youtube-tabulated-entries-append doesn't run any hook; I could
advice it of course, but wanted to check if  you had plans  to add
such a hook.

**Comment by isamert** [comment]
I added a hook called `empv-youtube-tabulated-new-entries-hook`. Let
me know if fully covers your use-case, because it simply works right
after adding entries and called on batch results, not per-entry.
