### ISSUE TITLE
Feature Request: Per-Query Results Buffer

### ISSUE THREAD

**Issue by tvraman** [isamert/empv.el#72]
* Feature Request: Create Per Query Results Buffer?

1. Now that we have the ability to pull more results, here is the next request.
2. At present, results get added to  the results buffer --- this is nice!
3. What is not so nice is that because we have one results buffer to
   hold them all, the results are now mixed.
4. Request: If we   named the results buffer as "*Results For <Q>*",
5. then we could acculumate results for a given query to its own
   buffer.

   Thoughts?

**Comment by isamert** [comment]
Yeah, I also thought about this while implementing _fetch more_
feature but it was non trivial to just slip this feature in. This is
also something that I have use cases for, I will take look at it at
some point.
