### ISSUE TITLE
Problem with not png thumbnails in empv-youtube-tabulated

### ISSUE THREAD

**Issue by adr-adr** [isamert/empv.el#73]
Hi, it seems that https://github.com/isamert/empv.el/commit/76e05dbadca55c96e02991d587141ba58f516a61 is 
setting image type to png, so jpg thumbnails are not shown in the results' buffer.

I'm getting in \*Messages\*:
Not a PNG file: ...

Oh, and thanks for this work, is quite handy!

**Comment by isamert** [comment]
Thanks for reporting!
