### ISSUE TITLE
New thumbnails are replacing old ones when search results are added

### ISSUE THREAD

**Issue by adr-adr** [isamert/empv.el#74]
Hi, there is a little bug that I'm sure you can correct easily. It should be a matter of adding an offset. Sorry I haven't study the code jet.

Let numbers represent thumbnails and letters the rest of the video description.
Imagine that you make a search and your tabulated results are:
1 a
2 b
3 c

If you make a new search in the *empv-yt-results* buffer, you'll get:
4 a
5 b
6 c
\- d
\- e
\- f
Instead of:
1 a
2 b
3 c
4 d
5 e
6 f

Regards

**Comment by isamert** [comment]
> It should be a matter of adding an offset. Sorry I haven't study the
> code jet.

Reporting the bugs is more than enough, thanks a lot!

Hopefully it's fixed, let me know if you encounter any other problem.
