### ISSUE TITLE
How to simply play a Youtube URL?

### ISSUE THREAD

**Issue by k4r4b3y** [isamert/empv.el#89]
I use elfeed to follow youtube channels.  Elfeed items contain a video URL of the following form: https://www.youtube.com/watch?v=4Dei2buz1X0

How do I play this URL with empv?  If it was terminal, I would simply use `mpv https://www.youtube.com/watch?v=4Dei2buz1X0`.  With empv, I select this youtube link (mark it as a region) and use `empv-play-thing-at-point`.  The URL gets played but **without video** (only audio is playing).  How do I get the video AND audio playing with empv.el with direct Youtube links?

**Comment by isamert** [comment]
You need to do `empv-toggle-video`. See the section named `Viewing YouTube videos` in the README. You may need to restart empv afterwards (`empv-exit`).

Also `empv-play-thing-at-point` should work without selecting the region, if your cursor is on the url (most of the time).

**Comment by k4r4b3y** [comment]
Yep, it worked.  So, before passing a Youtube URL to `empv-play-thing-at-point`, I run `M-x empv-toggle-video`.  Then, I move the cursor on the Youtube URL, and call `empv-play-thing-at-point`.  I get both audio and video playing.

**Comment by isamert** [comment]
Great! You can call `empv-toggle-video` at any time to hide/show the video.
